### ISSUE TITLE
Tagging Support in Resource and Request

### ISSUE THREAD

**Issue by d3ep4k** [metamug/openapi-rest#4]
Swagger specs add tags to request level. So we need tag attribute on request tag or we can add description inside 
the Request tag to support request level tags

https://swagger.io/docs/specification/grouping-operations-with-tags/

```xml
<Resource>
  <Desc>
    This resource is for customer operations
    <Tag name="customer-operations" color="#CAFE00"/>
  </Desc>
  <Request>
    <Desc>
      This request performs operations for the customer.
       <Tag name="customer-query" color="#00CAFE"/>
    </Desc>
  </Request>
</Resource>
```

**Comment by d3ep4k** [comment]
@richard937  add the tag as per swagger spec in the generated json as well. Part of the same issue. https://swagger.io/docs/specification/grouping-operations-with-tags/

**Comment by d3ep4k** [comment]
@richard937 this works while generating swagger docs? Please check and close this.

**Comment by richard937** [comment]
> @richard937 this works while generating swagger docs? Please check and close this.

Yes tagging is working
![tag](https://user-images.githubusercontent.com/42942897/86535628-4ada9b80-beff-11ea-8995-37950520cc71.PNG)
![testtag](https://user-images.githubusercontent.com/42942897/86535632-4f06b900-beff-11ea-88f1-08f721699915.PNG)
