### ISSUE TITLE
Project Relative path for output

### ISSUE THREAD

**Issue by d3ep4k** [metamug/openapi-rest#5]
```java
private final String outputFolder = "/Users/anishhirlekar/parser-output";
```

https://github.com/metamug/openapi-rest-model/blob/open-api/src/test/java/com/metamug/parser/parser/MarshalTest.java

try to put it in the project
you can make a folder in the project. where this can be printed
no need to hard code your computer's path, this will fail.

**Comment by ancode4** [comment]
MarshalTest.java is removed. Replaced by test files in 
https://github.com/metamug/openapi-rest-model/tree/open-api/src/test/java/com/metamug/parser/schema
